CREATE TABLE QUKI.Message(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  MesID TEXT NOT NULL,
  UserID INT(11) NOT NULL,
  FromID INT(11) DEFAULT NULL,
  State TINYINT(4) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1412
CHARACTER SET cp1251
COLLATE cp1251_general_ci;