CREATE TABLE QUKI.MessageText(
  MesID INT(11) NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(255) NOT NULL,
  `DateTime` DATETIME NOT NULL,
  PRIMARY KEY (MesID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 20
CHARACTER SET cp1251
COLLATE cp1251_general_ci;